# toml-docs-start main
[main]
    separator = "-"
    description = "Erik is a front-end developer based in Chicago."
    enableDarkMode = false
# toml-docs-end main

# toml-docs-start docs
[docs]
    version = "0.8"
    basePath = ""
# toml-docs-end docs

# toml-docs-start home
[home]
    sections = ["blog", "github-projects"]
    featurePhoto = "/img/sunrise.jpg" # source: https://unsplash.com/photos/ZX6BPboJrYk
    fullCover = false
# toml-docs-end home

# toml-docs-start navigation
[navigation]
    logo = "/img/logo_icon.svg"
    color = "light"
    style = "light"
    fixed = true
    offset = "4em"
    search = true
    breadcrumb = false
    toc = true
    sidebar = true
# toml-docs-end navigation

# toml-docs-start list
[list]
    [github-projects]
        title = "GitHub Projects"
        sort = "date"
        reverse = false
        cols = 3
        color = ""
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "stacked"
        style = "border-1 card-emphasize"
        homepage = 3
    [blog]
        title = "Blog"
        sort = "date"
        reverse = false
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-1"
        homepage = 3
# toml-docs-end list

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#f06449ff"
    secondary = "#5BC3EB"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#DADAD9"
    dark = "#36382E"
    background = "#EDE6E3"
# toml-docs-end theme-colors
    themeOpacity = "10"
# toml-docs-start font
    themeFont = "Inter"
    themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap"
# toml-docs-end font

[schema]
    type = "Organization"
    name = ""
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    # github = "https://github.com/gethinode/hinode"
    section = "blog"
    [author]
        name = "Erik Slagter"
        witter = "https://twitter.com/https://twitter.com/erikslagter"
        linkedin = "https://www.linkedin.com/in/slagtererik/"
        github = "https://github.com/erik06"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 

[links]
    bs_badge_heading = "https://getbootstrap.com/docs/5.2/components/badge/#headings"
    hinode_docs = "https://gethinode.com/docs"
    hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
    mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
    observatory = "https://observatory.mozilla.org/analyze/demo.gethinode.com"
    pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.gethinode.com%2F"
    utterances = "https://utteranc.es"
 