[[main]]
name = "Contact"
url = "/contact/"
weight = 40

[[main]]
name = "Blog"
url = "/blog/"
weight = 20

[[main]]
name = "Github Projects"
url = "/github-projects/"
weight = 10

[[main]]
name = "Sample project"
parent = "Github Projects"
url = "/github-projects/sample-project/"
weight = 1

[[main]]
name = "Another project"
parent = "Github Projects"
url = "/github-projects/another-project/"
weight = 2


[[social]]
name = "LinkedIn"
pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
url = "https://linkedin.com/in/slagtererik"
weight = 10

[[social]]
name = "GitHub"
pre = "<i class=\"fab fa-github fa-2x\"></i>"
url = "https://github.com/erik06"
weight = 20

[[social]]
name = "Twitter"
pre = "<i class=\"fab fa-twitter fa-2x\"></i>"
url = "https://twitter.com/erikslagter"
weight = 30

# toml-docs-start sample-navigation
[[sample]]
name = "Blog"
url = "/blog/"
weight = 10

[[sample]]
name = "Github Projects"
url = "/github projects/"
weight = 20

[[sample]]
name = "Sample project"
parent = "Github Projects"
url = "/github projects/sample-project/"
weight = 1

[[sample]]
name = "Another project"
parent = "Github Projects"
url = "/github projects/another-project/"
weight = 2
# toml-docs-end sample-navigation
